FROM --platform=linux/amd64 golang:1.23-alpine

RUN apk add --no-cache bash curl git make ca-certificates

# Copy over the config
WORKDIR /app/config
COPY ./configs/config.prod.yaml ./config.yaml

# Copy over the app
WORKDIR /app
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY . .

# Build the app & run it
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/run

EXPOSE 8080

CMD ["./main", "--config", "/app/config/config.yaml"]
